
/**
 * Client events.
 */
public enum ClientEvent {
    REGISTER_SUCCESS,
    REGISTER_FAILURE,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGOUT_SUCCESS,
    ROOM_LIST,
    ROOM_CREATED,
    ROOM_EXISTS,
    ROOM_JOINED,
    ROOM_LEFT,
    ROOM_NOT_FOUND,
    MESSAGE_RECEIVED,
    CONNECTION_LOST,
    CONNECTION_RESTORED,
    RECONNECTION_SUCCESS,
    RECONNECTION_FAILED
}
